name: Deploy

on:
  push:
    branches:
      - master
      - feature/5

jobs:
  build_wasm:
    name: Build WASM
    runs-on: ubuntu-latest

    steps:
      - name: Build WASM
        uses: ./.github/actions/wasm-action

  build_react_app:
    name: Build React App
    runs-on: ubuntu-latest
    needs: build_wasm

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1

      - name: Download WASM file
        uses: actions/download-artifact@v1
        with:
          name: main.wasm

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          cp -pr main.wasm ./public
          npm ci
          npm run build --if-present
          # npm test
          echo ${GITHUB_WORKSPACE}
          pwd
          ls -la
        env:
          CI: false

      - name: Upload build directory
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy_to_netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: build_react_app

    steps:
      # - uses: actions/checkout@master

      - name: Download build directory
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: check directory
        run: |
          echo ${GITHUB_WORKSPACE}
          pwd
          ls -la
          echo build dir
          ls ./build

      - name: deploy production
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NetlifyAuthToken }}
          NETLIFY_SITE_ID: ${{ secrets.NetlifySiteId }}
        with:
          args: deploy -p -d ./build
