name: Netlify

on:
  push:
    branches:
      - master
      - feature/5

jobs:
  build:
    name: Deploy netlify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: deploy production
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NetlifyAuthToken }}
        NETLIFY_SITE_ID: ${{ secrets.NetlifySiteId }}
      with:
        args: 'deploy -p -d ${GITHUB_WORKSPACE}/build'
